import '../models/banda_model.dart';
import '../models/documento_model.dart';
import '../models/proyecto_model.dart';

/// Proyecto de muestra al que cuelgan las [bandasDemo], usado SOLO por
/// [main_demo.dart] para mostrar el look & feel del panel administrativo
/// sin necesitar un proyecto de Firebase real todavía.
const proyectoDemo = ProyectoModel(
  id: 'demo-proyecto',
  nombre: 'La Grúa del Rock',
  tipo: 'Festival musical',
  descripcion: 'Escenario móvil itinerante de la Corporación de La Raíz.',
  estado: EstadoProyecto.enCurso,
  aceptaPostulacionesBandas: true,
);

/// Datos de muestra (bandas ficticias) usados SOLO por [main_demo.dart]
/// para mostrar el look & feel del dashboard y el detalle sin necesitar
/// un proyecto de Firebase real todavía.
final List<BandaModel> bandasDemo = [
  BandaModel(
    id: 'demo-1',
    proyectoId: proyectoDemo.id!,
    nombreGrupo: 'Los Fierros del Puerto',
    comuna: 'Talcahuano',
    generoMusical: 'Rock urbano',
    telefonoContacto: '+56 9 1234 5678',
    correoContacto: 'contacto@losfierrosdelpuerto.cl',
    nombreRepresentante: 'Marcelo Sepúlveda',
    rutRepresentante: '12.345.678-5',
    linkSpotify: 'https://open.spotify.com/artist/demo-fierros',
    linkYoutube: 'https://youtube.com/@losfierrosdelpuerto',
    linkInstagram: 'https://instagram.com/losfierrosdelpuerto',
    linkMaterialAudiovisual: 'https://drive.google.com/demo-fierros',
    dossierUrl: 'https://example.com/dossier-fierros.pdf',
    dossierNombreArchivo: 'dossier_fierros_2026.pdf',
    riderTecnicoUrl: 'https://example.com/rider-fierros.pdf',
    riderTecnicoNombreArchivo: 'rider_tecnico_fierros.pdf',
    estado: EstadoPostulacion.seleccionada,
    fechaPostulacion: DateTime.now().subtract(const Duration(days: 12)),
    fechaActualizacion: DateTime.now().subtract(const Duration(days: 2)),
  ),
  BandaModel(
    id: 'demo-2',
    nombreGrupo: 'Turbina Naranja',
    comuna: 'Concepción',
    generoMusical: 'Punk rock',
    telefonoContacto: '+56 9 8765 4321',
    correoContacto: 'turbinanaranja@gmail.com',
    nombreRepresentante: 'Javiera Contreras',
    rutRepresentante: '15.987.654-3',
    linkSpotify: 'https://open.spotify.com/artist/demo-turbina',
    linkYoutube: null,
    linkInstagram: 'https://instagram.com/turbinanaranja',
    linkMaterialAudiovisual: null,
    dossierUrl: 'https://example.com/dossier-turbina.pdf',
    dossierNombreArchivo: 'dossier_turbina_naranja.pdf',
    riderTecnicoUrl: null,
    riderTecnicoNombreArchivo: null,
    estado: EstadoPostulacion.pendiente,
    fechaPostulacion: DateTime.now().subtract(const Duration(days: 5)),
    fechaActualizacion: null,
  ),
  BandaModel(
    id: 'demo-3',
    nombreGrupo: 'Costanera Muerta',
    comuna: 'San Pedro de la Paz',
    generoMusical: 'Metal',
    telefonoContacto: '+56 9 5555 1122',
    correoContacto: 'booking@costaneramuerta.cl',
    nombreRepresentante: 'Rodrigo Muñoz',
    rutRepresentante: '9.876.543-2',
    linkSpotify: 'https://open.spotify.com/artist/demo-costanera',
    linkYoutube: 'https://youtube.com/@costaneramuerta',
    linkInstagram: 'https://instagram.com/costaneramuerta',
    linkMaterialAudiovisual: 'https://vimeo.com/demo-costanera',
    dossierUrl: 'https://example.com/dossier-costanera.pdf',
    dossierNombreArchivo: 'dossier_costanera_muerta.pdf',
    riderTecnicoUrl: 'https://example.com/rider-costanera.pdf',
    riderTecnicoNombreArchivo: 'rider_costanera.pdf',
    estado: EstadoPostulacion.rechazada,
    fechaPostulacion: DateTime.now().subtract(const Duration(days: 20)),
    fechaActualizacion: DateTime.now().subtract(const Duration(days: 15)),
  ),
  BandaModel(
    id: 'demo-4',
    nombreGrupo: 'Vientos del Bío-Bío',
    comuna: 'Chiguayante',
    generoMusical: 'Folk-rock',
    telefonoContacto: '+56 9 3344 5566',
    correoContacto: 'vientosdelbiobio@outlook.com',
    nombreRepresentante: 'Camila Torres',
    rutRepresentante: '18.222.333-4',
    linkSpotify: null,
    linkYoutube: 'https://youtube.com/@vientosdelbiobio',
    linkInstagram: 'https://instagram.com/vientosdelbiobio',
    linkMaterialAudiovisual: null,
    dossierUrl: 'https://example.com/dossier-vientos.pdf',
    dossierNombreArchivo: 'dossier_vientos_biobio.pdf',
    riderTecnicoUrl: null,
    riderTecnicoNombreArchivo: null,
    estado: EstadoPostulacion.pendiente,
    fechaPostulacion: DateTime.now().subtract(const Duration(days: 3)),
    fechaActualizacion: null,
  ),
  BandaModel(
    id: 'demo-5',
    nombreGrupo: 'Vapor Salvaje',
    comuna: 'Hualpén',
    generoMusical: 'Cumbia rock',
    telefonoContacto: '+56 9 7788 9900',
    correoContacto: 'vaporsalvaje.banda@gmail.com',
    nombreRepresentante: 'Diego Fuentes',
    rutRepresentante: '14.111.222-9',
    linkSpotify: 'https://open.spotify.com/artist/demo-vapor',
    linkYoutube: 'https://youtube.com/@vaporsalvaje',
    linkInstagram: 'https://instagram.com/vaporsalvaje',
    linkMaterialAudiovisual: 'https://drive.google.com/demo-vapor',
    dossierUrl: 'https://example.com/dossier-vapor.pdf',
    dossierNombreArchivo: 'dossier_vapor_salvaje.pdf',
    riderTecnicoUrl: 'https://example.com/rider-vapor.pdf',
    riderTecnicoNombreArchivo: 'rider_vapor_salvaje.pdf',
    estado: EstadoPostulacion.seleccionada,
    fechaPostulacion: DateTime.now().subtract(const Duration(days: 9)),
    fechaActualizacion: DateTime.now().subtract(const Duration(days: 1)),
  ),
  BandaModel(
    id: 'demo-6',
    nombreGrupo: 'Riel y Ceniza',
    comuna: 'Coronel',
    generoMusical: 'Reggae',
    telefonoContacto: '+56 9 2233 4455',
    correoContacto: 'rielyceniza@gmail.com',
    nombreRepresentante: 'Fernanda Vidal',
    rutRepresentante: '16.444.555-6',
    linkSpotify: 'https://open.spotify.com/artist/demo-riel',
    linkYoutube: 'https://youtube.com/@rielyceniza',
    linkInstagram: null,
    linkMaterialAudiovisual: null,
    dossierUrl: 'https://example.com/dossier-riel.pdf',
    dossierNombreArchivo: 'dossier_riel_y_ceniza.pdf',
    riderTecnicoUrl: null,
    riderTecnicoNombreArchivo: null,
    estado: EstadoPostulacion.pendiente,
    fechaPostulacion: DateTime.now().subtract(const Duration(days: 1)),
    fechaActualizacion: null,
  ),
];

/// Documentos institucionales de muestra para la pantalla de
/// "Documentación" del panel demo.
final List<DocumentoModel> documentosDemo = [
  DocumentoModel(
    id: 'doc-1',
    titulo: 'Estatutos Corporación de La Raíz',
    categoria: CategoriaDocumento.estatutos,
    descripcion: 'Estatutos vigentes, versión reducida ante notaría.',
    archivoUrl: 'https://example.com/documentos/estatutos-la-raiz.pdf',
    nombreArchivo: 'estatutos_la_raiz.pdf',
    storagePath: 'documentos_institucionales/doc-1/estatutos_la_raiz.pdf',
    tamanoBytes: 842000,
    fechaSubida: DateTime.now().subtract(const Duration(days: 210)),
  ),
  DocumentoModel(
    id: 'doc-2',
    titulo: 'Acta Directorio Marzo 2026',
    categoria: CategoriaDocumento.actas,
    descripcion: 'Acuerdos sobre la próxima edición de La Grúa del Rock.',
    archivoUrl: 'https://example.com/documentos/acta-marzo-2026.pdf',
    nombreArchivo: 'acta_directorio_marzo_2026.pdf',
    storagePath: 'documentos_institucionales/doc-2/acta_directorio_marzo_2026.pdf',
    tamanoBytes: 310000,
    fechaSubida: DateTime.now().subtract(const Duration(days: 45)),
  ),
  DocumentoModel(
    id: 'doc-3',
    titulo: 'Contrato arriendo camión escenario',
    categoria: CategoriaDocumento.contratos,
    descripcion: 'Contrato con transportes para "La Grúa del Rock" 2026.',
    archivoUrl: 'https://example.com/documentos/contrato-camion.pdf',
    nombreArchivo: 'contrato_camion_grua.pdf',
    storagePath: 'documentos_institucionales/doc-3/contrato_camion_grua.pdf',
    tamanoBytes: 1250000,
    fechaSubida: DateTime.now().subtract(const Duration(days: 30)),
  ),
  DocumentoModel(
    id: 'doc-4',
    titulo: 'Informe financiero Q1 2026',
    categoria: CategoriaDocumento.informes,
    descripcion: 'Rendición de fondos concursables e ingresos por eventos.',
    archivoUrl: 'https://example.com/documentos/informe-q1-2026.pdf',
    nombreArchivo: 'informe_financiero_q1_2026.pdf',
    storagePath: 'documentos_institucionales/doc-4/informe_financiero_q1_2026.pdf',
    tamanoBytes: 495000,
    fechaSubida: DateTime.now().subtract(const Duration(days: 15)),
  ),
  DocumentoModel(
    id: 'doc-5',
    titulo: 'Manual de identidad visual',
    categoria: CategoriaDocumento.otros,
    descripcion: 'Logos, tipografías y paleta de la Corporación.',
    archivoUrl: 'https://example.com/documentos/manual-marca.pdf',
    nombreArchivo: 'manual_identidad_visual.pdf',
    storagePath: 'documentos_institucionales/doc-5/manual_identidad_visual.pdf',
    tamanoBytes: 2100000,
    fechaSubida: DateTime.now().subtract(const Duration(days: 5)),
  ),
];
